const human = require("../assets/images/human.png");
const alien = require("../assets/images/alien.png");
const usersData = [
    {
      username: "Zorblax",
      image: human,
      race: "Human",
      gold: 100,
      attack: 80,
      defence: 70,
      health: 90,
    },
    {
      username: "Nebulae",
      image: alien,
      race: "Alien",
      gold: 50,
      attack: 90,
      defence: 60,
      health: 80,
    },
    {
      username: "Xandron",
      image: human,
      race: "Human",
      gold: 200,
      attack: 60,
      defence: 90,
      health: 70,
    },
    {
        
      username: "Zarquon",
      image: alien,
      race: "Alien",
      gold: 75,
      attack: 70,
      defence: 80,
      health: 60,
    },
    {
      username: "Astrolo",
      image: human,
      race: "Human",
      gold: 150,
      attack: 50,
      defence: 70,
      health: 75,
    },
    {
      username: "Xenomorph",
      image: alien,
      race: "Alien",
      gold: 25,
      attack: 85,
      defence: 50,
      health: 90,
    },
    {
      username: "Zarathustra",
      image: human,
      race: "Human",
      gold: 10,
      attack: 60,
      defence: 40,
      health: 50,
    },
    {
      username: "Nebulon",
      image: alien,
      race: "Alien",
      gold: 500,
      attack: 100,
      defence: 95,
      health: 100,
    },
    {
      username: "Galaxar",
      image: human,
      race: "Human",
      gold: 1000,
      attack: 95,
      defence: 100,
      health: 95,
    },
    {
      username: "Zetron",
      image: alien,
      race: "Alien",
      gold: 300,
      attack: 90,
      defence: 85,
      health: 80,
    },
  ];
  
  export default usersData;
  